---
- name: Deploy zipped Cart from Nexus on Slave 2
  hosts: ubuntu2
  become: true
  tasks:

   - name: Update Ubuntu to latest Patch
     ansible.builtin.apt:
       update_cache: yes

   - name: Ensure Python3, Pip are installed
     ansible.builtin.apt:
       name:
         - python3
         - pip
       state: present
       update_cache: yes

   - name: Unzip a file that is downloaded from Nexus
     ansible.builtin.unarchive:
       src: http://18.209.173.52:8081/repository/maven-releases/com/anil/cart/0.0.1/cart.zip
       dest: /home/ubuntu
       remote_src: yes

   - name: Install specified python requirements
     ansible.builtin.pip:
       name: Flask
       state: present

   - name: Execute cart using script module
     ansible.builtin.script: /home/ubuntu/app.py
